kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubetel
  namespace: "kube-system"
  labels:
    kcdapp: kubetel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: kubetel
        component: kubetel
    spec:
      nodeSelector:
        "node-role.kubernetes.io/master": ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
      # serviceAccountName: kcd
      # serviceAccount: kcd
      containers:
        - name: "kubetel"
          image: "evchee88/kubetel:latest"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081
            - name: dockerhub
              protocol: TCP
              containerPort: 5000
          args:
            - kubectl

---
kind: Service
apiVersion: v1
metadata:
  name: kubetel
  namespace: "kube-system"
  labels:
    app: kubetel
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubetel
---
kind: KCD
apiVersion: custom.k8s.io/v1
metadata:
  name: "kubetel"
  namespace: "kube-system"
spec:
  imageRepo: evchee88/kubetel
  tag: latest
  pollIntervalSeconds: 300
  selector:
    kcdapp: kubetel
  container:
    name: "kubetel"
  config:
    name: kubetel
    key: version
---
kind: ConfigMap
apiVersion: v1
data:
  version: latest
metadata:
  name: kubetel
  namespace: "kube-system"
