server:
  port: 80
controller:
  maxRetries: 2
  workercount: 2
tracker:
  maxRetries: 2
  workercount: 2
  endpoint: "https://sqs.us-west-1.amazonaws.com/951896542015/k8s-tracker-deploy-events-stages"
  endpointtype: sqs
log:
  level: trace
image: 951896542015.dkr.ecr.us-west-1.amazonaws.com/wish/kubetel
namespace: kube-system
